### ISSUE TITLE
Discussion on the automatic scaling of element of HtmlMesh

### ISSUE THREAD

**Issue by CTOSPACE** [BabylonJS/Extensions#267]
https://www.babylonjs-playground.com/#Y2LIXI#55

I have updated the latest HtmlMesh extension, and I think it may be necessary to further discuss the issue of automatic element scaling. If automatic scaling is not used, I need to clearly define the scaling or font size of the element to make it look more appropriate in the scene. Therefore, I have made some changes to the setContentPx code of HtmlMesh, reintroducing sizingElement and scaleElement. In my code, SizingElement is used to set the width and height, scaleElement is used to set the scaling. The display of sizingElement is flex, and the child elements are set to be vertically and horizontally centered, so that the size of scaleElement in the dom is the size of its child elements. The scaling ratio of scaleElement is calculated based on the width and height of sizingElement and the width and height of scaleElement according to the contain mode, The contain mode can be understood as the contain mode used by the background image of the div. In this case, the elements of the HtmlMesh will automatically adapt to the size of the HtmlMesh, so we don't have to try to define the width, height, or font size of the elements. It always performs well. I wrote a PG, https://www.babylonjs-playground.com/#Y2LIXI#55 In this PG, element A with an orange background in the bottom right corner is a direct dom element used for comparison, element B with a blue background is automatically scaled using contain mode, and element C with a red background is not automatically scaled using contain mode. The styles of these three elements, A, B, and C, are exactly the same except for the background, It can be seen that element B, which uses auto scaling, appears to behave the same as reference element A in the scene, while element C, which does not use auto scaling, behaves differently from reference element A. Auto scaling performed well in my project

Here are the relevant codes I have modified

![image](https://github.com/BabylonJS/Extensions/assets/1892162/6e8c5a1a-2d6c-4514-a992-c021d2e8581b)
![image](https://github.com/BabylonJS/Extensions/assets/1892162/3f3fb910-3742-4eda-b8ba-9e7e81dc7094)

@ericwood73

**Comment by ericwood73** [comment]
As I understand it, you are defining an element that can contain your content and then using that element to control how the content adapts to the size of the mesh.  It seems this would be used primarily with inline content vs an iframe.  Do you feel this belongs in the html mesh extension. e.g. does it need data that it can only obtain from the htmlMesh instance versus querying parent elements?  Or is this just a possible implementation of an element passed to HtmlMesh?  HtmlMesh does not and should not care generally about the nature of the html elements it renders.   Its only job is to render the HTML content to match the mesh scale, position, and orientation.  On the other hand, if this is something that you feel alot of devs are going to need to do and we can make it optional, as it appears you've done, I could see the value of including it.  I'm not a huge fan of the setTimeout 0.  Is that necessary because you have to wait for layout until you can measure the width and height of the dom element?  We can probably find a better way to do that, maybe an observable on ready.  Can you share some code or do a PR, so I can play with it?

**Comment by CTOSPACE** [comment]
I see，making it optional is valuable, I will push a pr after I modify the code well today

**Comment by ericwood73** [comment]
I see what you are saying now about contain.  I'm trying to make a slide for the presentation of this to the BJS meetup tomorrow and I want my title to be centered, but I need to scale it up to get it big enough and when I apply the scale, then it scales the div bigger than its parent.  I see you can set max width and object fit, but object fit doesn't work with divs.  So you need to compute the scale and scale the content to fit.  Go ahead and create a PR.  We can use your fit property to determine whether this behavior gets applied.  If it is none it does not.  If it is contain or stretch or whatever, then it does.  I think it would be a good addition.  Sorry it took me a bit to understand what you were trying to do.

**Comment by CTOSPACE** [comment]
Okay, I'm sorry, maybe I didn't understand the problem you described very well. I created some divs based on my understanding, but their performance still hasn't changed. Can you provide me with the code for testing divs? I hope you can see your reply in a timely manner. Can you provide me with a screenshot of the div code or paste a segment of the div code

@ericwood73

**Comment by ericwood73** [comment]
I agree with your idea to add a 'fit-mode' option in the HTMLMesh constructor. I now understand why it's easier to handle this in the HTMLMesh (since we need JavaScript to get the sizes). Let's ensure we include a 'fit-mode: none' option, which maintains the current behavior and is the default.  Please submit a PR with your changes.

**Comment by CTOSPACE** [comment]
it is very pleasure you agree with me, i had already pushed a pr a few days ago which include the 'sizeFit: none' by the default, please review it https://github.com/BabylonJS/Extensions/pull/270, If there is still any code that needs to be modified, I will complete the modifications in the shortest possible time

**Comment by ericwood73** [comment]
Thanks.  Just saw your PR.  I will review and get back to you with feedback.
